# docker-compose.yml
services:
  backend:
    build: ./backend
    container_name: portfolio_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # Mounts the local code into the container
      - portfolio_db_data:/app/data/db # Persists the database

  frontend:
    build: ./frontend
    container_name: portfolio_frontend
    restart: unless-stopped
    ports:
      - "3000:80" # Map host port 3000 to container port 80 (Nginx)
    depends_on:
      - backend

volumes:
  portfolio_db_data: