# docker-compose.yml
services:
  backend:
    build: ./backend
    container_name: portfolio_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - portfolio_db_data:/app

  frontend:
    build: ./frontend
    container_name: portfolio_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  portfolio_db_data: